# -*- coding: utf-8 -*-
"""LoEn_DataPreprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpAYNlI2nK4BFR7KquFIUYTd7qVttDW-
"""

from datasets import load_dataset
from tqdm.auto import tqdm
import numpy as np
from datasets import Dataset
import io

class GaussianNoise:
  def __init__(self, mean=0, std=0, n_noised_img=3):
    self.mean = mean
    self.std = std
    self.n_noised_img = n_noised_img

  def transform_type(self, image):
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)
    png_image = Image.open(buffer)
    return png_image

  def add_noise(self, img_arr):
    #convert a PIL Image to noisy PIL Image
    img_arr = np.array(image)

    noise = np.random.normal(mean, std, img_arr.shape).astype(np.int16)
    noised_img_arr = img_arr +  noise
    noised_img_arr = np.clip(noised_img_arr, 0, 255).astype(np.uint8)

    noised_img = Image.fromarray(noised_img_arr)
    noised_img = self.transform_type(noised_img)
    return noised_img

  def add_noise_data(self, dataset):
    gaussian_ds = []
    for c in tqdm(range(num_of_noised_imgs)):
            gaussian_ds.append({
                "image" : transform_type(gaussian_noised_img(img, 0, std_list[i])),
                "label" : label
            })
    return Dataset.from_list(gaussian_ds)
